adresse:
    path:     /{page}
    defaults: { _controller: "DomiAdresseBundle:Adresse:index",page:1 }
    requirements:
        page: \d+


adresse_show:
    path:     /show/{id}
    defaults: { _controller: "DomiAdresseBundle:Adresse:show" }

adresse_new:
    path:     /new
    defaults: { _controller: "DomiAdresseBundle:Adresse:new" }

adresse_create:
    path:     /create
    defaults: { _controller: "DomiAdresseBundle:Adresse:create" }
    methods:  POST

adresse_edit:
    path:     /edit/{id}
    defaults: { _controller: "DomiAdresseBundle:Adresse:edit" }

adresse_update:
    path:     /update/{id}
    defaults: { _controller: "DomiAdresseBundle:Adresse:update" }
    methods:  [POST, PUT]

adresse_delete:
    path:     /delete/{id}
    defaults: { _controller: "DomiAdresseBundle:Adresse:delete" }
    methods:  [POST, DELETE]
