individu:
    path:     /{page}
    defaults: { _controller: "DomiAdresseBundle:Individu:index",page:1 }
    requirements:
        page: \d+

individu_show:
    path:     /show/{id}
    defaults: { _controller: "DomiAdresseBundle:Individu:show" }
    requirements:
        page: \d+

individu_new:
    path:     /new
    defaults: { _controller: "DomiAdresseBundle:Individu:new" }

individu_create:
    path:     /create
    defaults: { _controller: "DomiAdresseBundle:Individu:create" }
    methods:  POST

individu_edit:
    path:     /edit/{id}
    defaults: { _controller: "DomiAdresseBundle:Individu:edit" }
    requirements:
        page: \d+

individu_update:
    path:     /update/{id}
    defaults: { _controller: "DomiAdresseBundle:Individu:update" }
    methods:  [POST, PUT]
    requirements:
        page: \d+

individu_delete:
    path:     /delete/{id}
    defaults: { _controller: "DomiAdresseBundle:Individu:delete" }
    methods:  [POST, DELETE]
    requirements:
        page: \d+
