ville:
    path:     /{page}
    defaults: { _controller: "DomiAdresseBundle:Ville:index",page:1 }
    requirements:
          page: \d+

ville_show:
    path:     /show/{id}
    defaults: { _controller: "DomiAdresseBundle:Ville:show" }

ville_new:
    path:     /new
    defaults: { _controller: "DomiAdresseBundle:Ville:new" }

ville_create:
    path:     /create
    defaults: { _controller: "DomiAdresseBundle:Ville:create" }
    methods:  POST

ville_edit:
    path:     /edit/{id}
    defaults: { _controller: "DomiAdresseBundle:Ville:edit" }

ville_update:
    path:     /update/{id}
    defaults: { _controller: "DomiAdresseBundle:Ville:update" }
    methods:  [POST, PUT]

ville_delete:
    path:     /delete/{id}
    defaults: { _controller: "DomiAdresseBundle:Ville:delete" }
    methods:  [POST, DELETE]
