domi_film_notefilm:
    resource: "@DomiFilmBundle/Resources/config/routing/notefilm.yml"
    prefix:   /notefilm


domi_film_film:
    resource: "@DomiFilmBundle/Resources/config/routing/film.yml"
    prefix:   /film

