#services:
##    domi_film.example:
##        class: Domi\Bundle\AdresseBundle\Example
##        arguments: [@service_id, "plain_value", %parameter%]
#domi_film_ville:
#  class: "%domi_film.ville.class%"
#  arguments: type="service" id="service_id"
#  arguments: plain_value
#  arguments: "%parameter_name%"