<?php

namespace Domi\Bundle\DocuBundle\Entity {

    use Doctrine\ORM\EntityRepository;

    /**
     * DocumentRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class DocumentRepository extends EntityRepository {

        /**
         * @return array
         */
        public function findAllOrderedByTitre() {
            return $this->getEntityManager()
                ->createQuery(
                    'SELECT d FROM DomiDocuBundle:Document d ORDER BY d.titre ASC'
                )
                ->getResult();
        }
    }
}
