
film_new:
    path:     /new
    defaults: { _controller: "DomiFilmBundle:Film:new"}

film_show:
    path:     /{id}/show
    defaults: { _controller: "DomiFilmBundle:Film:show" }

film_create:
    path:     /create
    defaults: { _controller: "DomiFilmBundle:Film:create" }
    methods:  POST


film_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomiFilmBundle:Film:edit" }
    requirements:
        id: \d+

film_update:
    path:     /{id}/update
    defaults: { _controller: "DomiFilmBundle:Film:update" }
    methods:  [POST, PUT]
    requirements:
        id: \d+


film_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomiFilmBundle:Film:delete" }
    methods:  [POST, DELETE]
    requirements:
        id: \d+

film:
    path:     /{page}
    defaults: { _controller: "DomiFilmBundle:Film:index", page:1 }
    requirements:
        id: \d+
