notefilm:
    path:     /
    defaults: { _controller: "DomiFilmBundle:Notefilm:index" }

notefilm_show:
    path:     /{id}/show
    defaults: { _controller: "DomiFilmBundle:Notefilm:show" }

notefilm_new:
    path:     /new
    defaults: { _controller: "DomiFilmBundle:Notefilm:new" }

notefilm_create:
    path:     /create
    defaults: { _controller: "DomiFilmBundle:Notefilm:create" }
    methods:  POST

notefilm_edit:
    path:     /{id}/edit
    defaults: { _controller: "DomiFilmBundle:Notefilm:edit" }

notefilm_update:
    path:     /{id}/update
    defaults: { _controller: "DomiFilmBundle:Notefilm:update" }
    methods:  [POST, PUT]

notefilm_delete:
    path:     /{id}/delete
    defaults: { _controller: "DomiFilmBundle:Notefilm:delete" }
    methods:  [POST, DELETE]
